// <auto-generated />
namespace Test.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FirstCmt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FirstCmt));
        
        string IMigrationMetadata.Id
        {
            get { return "201508131622380_FirstCmt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
